project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),

    path('users/', include('users.urls')),
    path('repairs/', include('repairs.urls'), name="repairs"),
]

repairs/urls.py
from django.urls import path

from repairs.views import (
    CreateRepair, ListRepairs, DetailRepair,
)

app_name = "repairs"

urlpatterns = [
    path('', ListRepairs.as_view(), name='list'),
    path('create/', CreateRepair.as_view(), name='create'),
    path('detail/<int:repair_id>', DetailRepair.as_view(), name='detail'),

]

users/urls.py
from django.urls import path, include

from users.views import Register

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('register/', Register.as_view(), name='register'),
]

templates/partials/menu.html
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'home' %}">Главная</a>
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'repairs:list' %}">Все заявки</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Выход</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Вход</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
        </li>
    {% endif %}
</ul>